### ISSUE TITLE
Login doesn't handle server pool FQDN

### ISSUE THREAD

**Issue by SarvaiD** [BroadSoft-Xtended/Project-Chrome-Extension#1] opened 2013-10-23 14:42 UTC
When configuring the server URL,  a pool FQDN is typically used to support multiple XSPs.  The client receives a 302 Found with a new location.  Here is an example:

URL Entered:  http://voice.dsci-net.com
DNS lookup returns 2 A Records:  ews1.dsci-net.com; ews2.dsci-net.com
Client then request using host: voice.dsci-net.com to one of the above A records
Response:  302 Found, with a header "Location:  http://ews1.dsci-net.com...."

The client should resend the initial request to the specific location which changes the host to ews1 or ews2.dsci-net.com.

Please also make sure when the server FQDN is used, and multiple results are returned, the client will try each if there is a connection problem:

I can provide a wireshark of the issue privately.

**Comment by jaimechieng** [comment] 2013-10-23 20:29
I am having the same issue. 302 redirect is ignored and the application gets a credentials invalid message. I can get the app to work if I point to a single XSP.

**Comment by broadsoftxtended** [comment] 2013-10-23 21:59
Thank you for you feedback. We are currently looking into some connection reconnection logic that is causing this problem. 

Also, as noted by you it does not currently support FQDNs. The problems you are seeing are due to setting a FQDN and then the faulty reconnection logic kicking in when the DNS cache updates (i.e. switches to the other xsp).

**Comment by broadsoftxtended** [comment] 2013-10-24 04:49
I'm not sure we can get this to work with FQDNs. The problem is that ajax requests don't have much control over 302s. There isn't a way to get the redirect location header from the response and use it in subsequent requests.

AFAIK, the only solution is to use a dedicated XSP. AJAX guru's in the community care to comment?

**Comment by broadsoftxtended** [comment] 2014-02-07 14:56
Closing issue. The code has been updated to handle a cluster FQDN, though we don't recommend using one because it could cause a lot of connection/re-connections if the resolution switches frequently between XSP's.

**Closed as completed by broadsoftxtended** 2014-02-07 14:56 UTC
Labels: wontfix
